import { TableOrders } from '@/components/auth/orders/table-orders'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Kuche | Pedidos',
  description: 'Generated by create next app',
}
export default function OrdersPage() {
  return (
    <div className="flex flex-col gap-4 p-8">
      <header className="mb-4">
        <h1 className="text-4xl font-bold">Pedidos</h1>
        <p className="text-sm text-muted-foreground">
          Acompanhe os pedidos feito pelo seus clientes
        </p>
      </header>
      <TableOrders />
    </div>
  )
}
